set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(OSXCROSS_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../../../third_party/osxcross")
set(CMAKE_OSX_DEPLOYMENT_TARGET "10.13")
set(CMAKE_OSX_SYSROOT "${OSXCROSS_DIR}/target/SDK/MacOSX15.5.sdk")

set(CMAKE_C_COMPILER "${OSXCROSS_DIR}/target/bin/x86_64-apple-darwin24.5-clang")
set(CMAKE_CXX_COMPILER "${OSXCROSS_DIR}/target/bin/x86_64-apple-darwin24.5-clang++")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
